version: '4'
services:
  hairstyle-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped